# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0010_remove_testreference_athlete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=30, unique=True, verbose_name='N\xfamero de documento')),
                ('phone', models.CharField(max_length=15, verbose_name='Tel\xe9fono')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electr\xf3nico')),
                ('support', models.FileField(upload_to='uploads/events/supports/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del evento')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(verbose_name='Finalizaci\xf3n')),
                ('price', models.FloatField(verbose_name='Costo (opcional)')),
                ('attachment', models.FileField(upload_to='uploads/events/atachments/', verbose_name='Adjunto')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Sport', verbose_name='Deporte')),
            ],
        ),
    ]
