# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170110_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Inscripciones abiertas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.AppUser', verbose_name='Organizador'),
        ),
    ]
