# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170110_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo (opcional)'),
        ),
    ]
