# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170110_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/events/atachments/', verbose_name='Adjunto'),
        ),
    ]
