# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170110_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Evento'),
            preserve_default=False,
        ),
    ]
