# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_contestant_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
    ]
