# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='cid',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
    ]
