# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170110_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
