# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-06 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20161121_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='creation_date',
            field=models.DateField(auto_created=True),
        ),
    ]
