# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('A', 'Aprobado'), ('E', 'Ejecuci\xf3n'), ('F', 'Finalizado')], max_length=1, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(max_length=100, verbose_name='Registro')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('A', 'Aprobado'), ('E', 'Ejecuci\xf3n'), ('F', 'Finalizado')], max_length=1, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subprogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('A', 'Aprobado'), ('E', 'Ejecuci\xf3n'), ('F', 'Finalizado')], max_length=1, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program', verbose_name='Programa')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='subprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Subprogram', verbose_name='Subprograma'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Province'),
        ),
    ]
