# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(max_length=100, verbose_name='Registro')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Aprobado'), ('E', 'Ejecuci\xf3n'), ('F', 'Finalizado')], max_length=1, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(default='', verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('A', 'Aprobado'), ('E', 'Ejecuci\xf3n'), ('F', 'Finalizado')], default='E', max_length=1, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subprogram',
            name='description',
            field=models.TextField(default='', verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subprogram',
            name='status',
            field=models.CharField(choices=[('A', 'Aprobado'), ('E', 'Ejecuci\xf3n'), ('F', 'Finalizado')], default='E', max_length=1, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='project',
            name='subprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Subprogram'),
        ),
    ]
