# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20160919_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
