# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:40
from __future__ import unicode_literals

import athletes.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('R', 'Registro Civil'), ('T', 'Tarjeta de Identidad'), ('C', 'C\xe9dula de Ciudadan\xeda'), ('E', 'C\xe9dula de Extranjer\xeda')], max_length=1, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=30, unique=True, verbose_name='N\xfamero de documento')),
                ('phone', models.CharField(max_length=15, verbose_name='Tel\xe9fono')),
                ('genre', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='G\xe9nero')),
                ('rh', models.CharField(choices=[('AP', 'A+'), ('AM', 'A-'), ('ABP', 'AB+'), ('ABM', 'AB-'), ('BP', 'B+'), ('BM', 'B-'), ('OP', 'O+'), ('OM', 'O-')], max_length=3, verbose_name='RH')),
                ('address', models.CharField(max_length=30, verbose_name='Direcci\xf3n')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electr\xf3nico')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('birthplace', models.CharField(max_length=50, verbose_name='Lugar de nacimiento')),
                ('school_level', models.CharField(choices=[('P', 'Primaria'), ('S', 'Secundario'), ('T', 'Media T\xe9cnica'), ('U', 'Universidad')], max_length=20, verbose_name='Nivel de estudios')),
                ('institution', models.CharField(max_length=50, verbose_name='Institucion educativa')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=athletes.models.get_path, verbose_name='Foto')),
                ('dni_support', models.FileField(upload_to=athletes.models.get_path, verbose_name='Copia del documento de identidad')),
                ('contact_fullname', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='Tel\xe9fono')),
                ('contact_address', models.CharField(max_length=70, verbose_name='Direcci\xf3n')),
                ('contact_mail', models.EmailField(max_length=50, verbose_name='Correo electr\xf3nico')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Municipality', verbose_name='Municipio')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Province', verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SportsTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Categor\xeda')),
                ('modality', models.CharField(max_length=50, verbose_name='Modalidad')),
                ('admission_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Club', verbose_name='Club')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.League', verbose_name='Liga')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Sport', verbose_name='Deporte')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='athlete',
            unique_together=set([('document_type', 'document_number')]),
        ),
    ]
