# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('R', 'Registro Civil'), ('T', 'Tarjeta de Identidad'), ('C', 'C\xe9dula de Ciudadan\xeda'), ('E', 'C\xe9dula de Extranjer\xeda')], max_length=1, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=30, verbose_name='N\xfamero de documento')),
                ('phone', models.CharField(max_length=15, verbose_name='Tel\xe9fono')),
                ('address', models.CharField(max_length=30, verbose_name='Direcci\xf3n')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electr\xf3nico')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('birthplace', models.CharField(max_length=50, verbose_name='Lugar de nacimiento')),
                ('school_level', models.CharField(choices=[('P', 'Primaria'), ('S', 'Secundario'), ('T', 'Media T\xe9cnica'), ('U', 'Universidad')], max_length=20, verbose_name='Nivel de estudios')),
                ('institution', models.CharField(max_length=50, verbose_name='Institucion educativa')),
                ('photo', django_resized.forms.ResizedImageField(upload_to=b'', verbose_name='Foto')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Municipality', verbose_name='Municipio')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Province', verbose_name='Provincias')),
            ],
        ),
    ]
