# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='document_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='N\xfamero de documento'),
        ),
        migrations.AlterUniqueTogether(
            name='athlete',
            unique_together=set([('document_type', 'document_number')]),
        ),
    ]
