# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='athletes.League', verbose_name='Liga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='athletes.Sport', verbose_name='Deporte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
