# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20160904_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to='uploads/avatars', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Province', verbose_name='Provincia'),
        ),
    ]
