# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_result_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='markreference',
            name='result_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='result_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
