# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20160928_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='clothes_size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=3, verbose_name='Talla de ropa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='eps_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='healthcare',
            field=models.CharField(choices=[('E', 'EPS'), ('S', 'SISBEN')], default='', max_length=1, verbose_name='Regimen de Salud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='shoes_size',
            field=models.IntegerField(default=10, verbose_name='Talla de zapatos'),
            preserve_default=False,
        ),
    ]
