# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_auto_20160919_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='G\xe9nero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='rh',
            field=models.CharField(choices=[('AP', 'A+'), ('AM', 'A-'), ('ABP', 'AB+'), ('ABM', 'AB-'), ('BP', 'B+'), ('BM', 'B-'), ('OP', 'O+'), ('OM', 'O-')], default='OM', max_length=3, verbose_name='RH'),
            preserve_default=False,
        ),
    ]
