# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_auto_20160928_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstab',
            name='modality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modalidad'),
        ),
    ]
