# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_auto_20160929_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstab',
            name='activity_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio en el deporte'),
            preserve_default=False,
        ),
    ]
