# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_auto_20161010_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropometricvaloration',
            name='body_weight',
            field=models.FloatField(verbose_name='Peso corporal (Kg)'),
        ),
    ]
