# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20161024_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstab',
            name='priorization',
            field=models.CharField(choices=[('0', 'No priorizado'), ('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3')], default='0', max_length=1, verbose_name='Priorizaci\xf3n'),
        ),
    ]
