# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_sportstab_priorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstab',
            name='functional',
            field=models.CharField(default='', max_length=1, verbose_name='Clasificaci\xf3n funcional (Solo deporte paral\xedmpico)'),
            preserve_default=False,
        ),
    ]
