# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_sportstab_functional'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaltest',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testreference',
            name='athlete',
            field=models.CharField(default='', max_length=100, verbose_name='Deportista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testreference',
            name='intl',
            field=models.BooleanField(default=False, verbose_name='Internacional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antropometricvaloration',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.BiomedicTab', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='aptitudetest',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.BiomedicTab', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='physiologicaltest',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.BiomedicTab', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='psicologicvaloration',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.BiomedicTab', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sfpbvaloration',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.BiomedicTab', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sportstab',
            name='functional',
            field=models.CharField(blank=True, max_length=10, verbose_name='Clasificaci\xf3n funcional (Solo deporte paral\xedmpico)'),
        ),
    ]
