# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '__first__'),
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('1', '0 a 5 A\xf1os'), ('2', '6 a 12 A\xf1os'), ('3', '13 a 17 A\xf1os'), ('4', '18 a 29 A\xf1os'), ('5', '30 a 59 A\xf1os'), ('6', 'M\xe1s de 60 A\xf1os')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('M', 'Mestizos'), ('I', 'Ind\xedgenas'), ('C', 'Campesinos'), ('D', 'Discapacitados'), ('A', 'Afrodescendientes')], max_length=2)),
                ('femenine_individuals', models.IntegerField()),
                ('masculine_individuals', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.BeneficiaryCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=60, verbose_name='Barrio/Vereda')),
                ('address', models.CharField(max_length=100, verbose_name='Direcci\xf3n')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor', verbose_name='Contratista')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Municipality', verbose_name='Municipio')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Province', verbose_name='Provincia')),
                ('subprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Subprogram', verbose_name='Subprograma')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Intervention')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Mi\xe9rcoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes')], max_length=2)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Intervention')),
            ],
        ),
    ]
