# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_beneficiarycategory_beneficiarygroup_intervention_session_timeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarycategory',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contractors.Session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervention',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor', verbose_name='Contratista'),
        ),
    ]
