# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 18:51
from __future__ import unicode_literals

import contractors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_auto_20161101_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='evidence',
            field=models.ImageField(default='', upload_to=contractors.models.get_interv_path, verbose_name='Evidencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervention',
            name='latitude',
            field=models.CharField(max_length=20, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='longitude',
            field=models.CharField(max_length=20, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='day',
            field=models.CharField(choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Mi\xe9rcoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes'), ('Sa', 'S\xe1bado'), ('Do', 'Domingo')], max_length=2),
        ),
    ]
