# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 17:54
from __future__ import unicode_literals

import contractors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_auto_20161121_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='observations',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='plist',
            field=models.ImageField(default='', upload_to=contractors.models.get_interv_path, verbose_name='Lista de personas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formationitem',
            name='support',
            field=models.FileField(upload_to=contractors.models.get_support_path, verbose_name='Soporte'),
        ),
        migrations.AlterField(
            model_name='sportsachievements',
            name='support',
            field=models.FileField(upload_to=contractors.models.get_support_path, verbose_name='Soporte'),
        ),
    ]
