# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_auto_20161122_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=30, unique=True, verbose_name='N\xfamero de documento')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('social_group', models.CharField(choices=[('M', 'Mestizos'), ('I', 'Ind\xedgenas'), ('C', 'Campesinos'), ('D', 'Discapacitados'), ('A', 'Afrodescendientes')], max_length=1, verbose_name='Grupo social')),
                ('interv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Intervention')),
            ],
        ),
    ]
