# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0009_member_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='interv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Intervention', verbose_name='Grupo'),
        ),
    ]
